logging:
  file: sample_runs/new.log
  pattern:
    file: "%msg%n"
  level:
    ROOT: 'debug'
    jndi: 'warn'
    org.eclipse.jetty: 'warn'
    org.jose4j: 'warn'
    org.springframework: 'warn'

spring:
  main:
    banner-mode: 'off'
